{
 "title": "MT_EX",
 "time": { "from": "2025-08-27T14:32:43.622Z", "to": "2025-09-04T03:57:08.475Z" },
 "templating": {
  "list": [
   {
    "name": "table",
    "label": "Experiments",
    "query": "SELECT DISTINCT name FROM experiments WHERE active = true"
   },
   { "name": "sample_rate", "label": "Sample Rate", "query": "1s" },
   {
    "name": "SNI",
    "label": "SNI",
    "query": "SELECT DISTINCT  tls_sni FROM packets_$table WHERE $__timeFilter(ts) AND tls_sni != ''"
   },
   {
    "name": "ip_scr_type",
    "label": "IP src type",
    "query": "SELECT DISTINCT ip_src_type FROM packets_$table WHERE $__timeFilter(ts) AND tls_sni != ''"
   },
   {
    "name": "ip_dst_type",
    "label": "IP dst type",
    "query": "SELECT DISTINCT ip_dst_type FROM packets_$table WHERE $__timeFilter(ts) AND tls_sni != ''"
   }
  ]
 },
 "panels": [
  {
   "title": "Click the button below to search and set the full timeline of $table",
   "type": "williamvenner-timepickerbuttons-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT MIN(ts) AS time_from, MAX(ts) AS time_to FROM packets_${table}",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Transferred per Sample Rate ($sample_rate) for each ip_dst, tls_sni",
     "type": "timeseries",
     "description": "This panel visualizes the sum of bytes transmitted per sample rate over time, helping to analyze data flow trends effectively.",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "rawSql": "SELECT ip_src, ip_dst, ts as time, sum(frame_len) as ' ', tls_sni \r\nFROM packets_${table} \r\nWHERE \r\n  $__timeFilter(ts) AND \r\n  tls_sni ~ '${SNI:regex}' AND \r\n  ip_src_type ~ '${ip_scr_type:regex}' AND\r\n  ip_dst_type ~ '${ip_dst_type:regex}'\r\nSAMPLE BY ${sample_rate} ALIGN TO CALENDAR\r\nORDER BY ts ASC"
      }
     ]
    }
   ]
  },
  { "title": "Packets Egress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Netify IP GeoHeatMap Egress",
   "type": "geomap",
   "description": "A Heat map which shows the GeoIP of the connected IPs and the relative weight which is based on how many times an IP has been seen in the traffic capture.",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  count(ip_dst_netify_geo_country) as pkts,\r\n  ip_dst_netify_geo_continent as continent,\r\n  ip_dst_netify_geo_country as country,\r\n  ip_dst_netify_geo_city as city,\r\n  ip_dst_netify_geo_lon AS longitude,\r\n  ip_dst_netify_geo_lat as latitude\r\nFROM packets_${table} \r\nWHERE \r\n  $__timeFilter(ts) AND \r\n  tls_sni ~ '${SNI:regex}' AND \r\n  ip_src_type ~ '${ip_scr_type:regex}' AND\r\n  ip_dst_type ~ 'PUBLIC' AND\r\n  ip_dst_netify_geo_lon != 0.0 AND\r\n  ip_dst_netify_geo_lat != 0.0\r\nGROUP BY \r\n  ip_dst_netify_geo_country,\r\n  ip_dst_netify_geo_city,\r\n  ip_dst_netify_geo_continent, \r\n  ip_dst_netify_geo_lon, \r\n  ip_dst_netify_geo_lat",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Netify IPs Geo distribution Egress",
   "type": "piechart",
   "description": "This panel visualizes the geographical distribution of outgoing IP addresses, highlighting the diversity in traffic sources for enhanced network analysis.",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 7 }
   ]
  },
  {
   "title": "TLS ALPN Egress",
   "type": "piechart",
   "description": "This panel visualizes the distribution of TLS Application-Layer Protocol Negotiation (ALPN) identifiers in outbound traffic",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT tls_alpn, count(*) as n\r\nFROM packets_$table \r\nWHERE \r\n  $__timeFilter(ts) AND \r\n  tls_sni ~ '${SNI:regex}' AND \r\n  ip_src_type ~ '${ip_scr_type:regex}' AND\r\n  ip_dst_type ~ 'PUBLIC'\r\nGROUP BY tls_alpn",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "TLS SNI Egress",
   "type": "piechart",
   "description": "This panel visualizes the distribution of TLS SNI (Server Name Indication) egress traffic",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  count(tls_sni) as pkts,\r\n  tls_sni as app,\r\nFROM packets_${table} \r\nWHERE \r\n  $__timeFilter(ts) AND \r\n  tls_sni ~ '${SNI:regex}' AND \r\n  ip_src_type ~ '${ip_scr_type:regex}' AND\r\n  ip_dst_type ~ 'PUBLIC'\r\nGROUP BY \r\n  tls_sni",
     "selectedFormat": 2
    }
   ]
  },
  { "title": "Netify Egress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Netify Hostname TLS SNI Application Tag Bytes Transferred per Sample Rate ($sample_rate)",
   "type": "timeseries",
   "description": "This panel visualizes the distribution of egress packets by extracting the hostname from the TLS SNI (Server Name Indication) information. It sends this hostname to Netify to retrieve data about the type of application associated with it. This analysis focuses solely on egress traffic, allowing for a detailed examination of traffic metrics linked to specific application identifiers behind each hostname.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT tls_sni_netify_app_tag as app, ts as time, sum(frame_len) as ' ',\r\nFROM packets_${table} \r\nWHERE \r\n  $__timeFilter(ts) AND\r\n  tls_sni ~ '${SNI:regex}' AND \r\n  ip_src_type ~ '${ip_scr_type:regex}' AND\r\n  ip_dst_type ~ 'PUBLIC'\r\nSAMPLE BY ${sample_rate} ALIGN TO CALENDAR\r\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Netify Hostname TLS SNI Application Tag Bytes Transferred per Sample Rate ($sample_rate)",
   "type": "timeseries",
   "description": "This panel visualizes the distribution of egress packets by extracting the hostname from the TLS SNI (Server Name Indication) information. It sends this hostname to Netify to retrieve data about the type of application associated with it. This analysis focuses solely on egress traffic, allowing for a detailed examination of traffic metrics linked to specific application identifiers behind each hostname.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT tls_sni_netify_app_tag as app, ip_dst_netify_geo_country as country, ts as time, sum(frame_len) as ' ',\r\nFROM packets_${table} \r\nWHERE \r\n  $__timeFilter(ts) AND\r\n  tls_sni ~ '${SNI:regex}' AND \r\n  ip_src_type ~ '${ip_scr_type:regex}' AND\r\n  ip_dst_type ~ 'PUBLIC'\r\nSAMPLE BY ${sample_rate} ALIGN TO CALENDAR\r\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Netify IP RDNS Application Tag Egress",
   "type": "piechart",
   "description": "This panel visualizes the distribution of egress application tags for Netify IPs. It takes the IP address, sends it to Netify, which performs a reverse DNS lookup to gather information about the application associated with the IP. This analysis focuses specifically on egress traffic, helping to track and understand the types of applications generating outgoing packets.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  count(ip_dst_netify_app_tag) as pkts,\r\n  ip_dst_netify_app_tag as app,\r\nFROM packets_${table} \r\nWHERE \r\n  $__timeFilter(ts) AND \r\n  tls_sni ~ '${SNI:regex}' AND \r\n  ip_src_type ~ '${ip_scr_type:regex}' AND\r\n  ip_dst_type ~ 'PUBLIC'\r\nGROUP BY \r\n  ip_dst_netify_app_tag",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Netify Hostname TLS SNI Application Tag Egress",
   "type": "piechart",
   "description": "This panel visualizes the distribution of egress packets by extracting the hostname from the TLS SNI (Server Name Indication) information. It sends this hostname to Netify to retrieve data about the type of application associated with it. This analysis focuses solely on egress traffic, allowing for a detailed examination of traffic metrics linked to specific application identifiers behind each hostname.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  count(tls_sni_netify_app_tag) as pkts,\r\n  tls_sni_netify_app_tag as app,\r\nFROM packets_${table} \r\nWHERE \r\n  $__timeFilter(ts) AND \r\n  tls_sni ~ '${SNI:regex}' AND \r\n  ip_src_type ~ '${ip_scr_type:regex}' AND\r\n  ip_dst_type ~ 'PUBLIC'\r\nGROUP BY \r\n  tls_sni_netify_app_tag",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Netify IP RDNS Application Category Tag Egress",
   "type": "piechart",
   "description": "This panel visualizes the distribution of egress packets categorized by Netify IP application tags. It processes the IP addresses, sending them to Netify for reverse DNS lookups, which retrieve information about the application categories associated with each IP. This analysis focuses specifically on egress traffic, providing insights into the types of applications that are being accessed based on their destination categories.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  count(ip_dst_netify_app_category_tag) as pkts,\r\n  ip_dst_netify_app_category_tag as app,\r\nFROM packets_${table} \r\nWHERE \r\n  $__timeFilter(ts) AND \r\n  tls_sni ~ '${SNI:regex}' AND \r\n  ip_src_type ~ '${ip_scr_type:regex}' AND\r\n  ip_dst_type ~ 'PUBLIC'\r\nGROUP BY \r\n  ip_dst_netify_app_category_tag",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Netify Hostname TLS SNI Application Category Tag Egress",
   "type": "piechart",
   "description": "This panel visualizes the distribution of egress packets categorized by TLS SNI application tags. It takes the hostname from the TLS SNI, sends it to Netify, and retrieves data about the application category associated with that hostname. This analysis focuses exclusively on egress traffic, helping to identify traffic patterns and application usage based on the categorized information obtained from the hostname.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  count(tls_sni_netify_app_category_tag) as pkts,\r\n  tls_sni_netify_app_category_tag as app,\r\nFROM packets_${table} \r\nWHERE \r\n  $__timeFilter(ts) AND \r\n  tls_sni ~ '${SNI:regex}' AND \r\n  ip_src_type ~ '${ip_scr_type:regex}' AND\r\n  ip_dst_type ~ 'PUBLIC'\r\nGROUP BY \r\n  tls_sni_netify_app_category_tag",
     "selectedFormat": 2
    }
   ]
  }
 ]
}